/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2009 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Data declarations

extern _UNKNOWN start; // weak
extern char s[]; // idb
extern int _CTOR_LIST__; // weak
extern int _DTOR_LIST__[]; // weak
extern _UNKNOWN _DTOR_END__; // weak
extern int _JCR_LIST__; // weak
extern char completed_6159; // weak
extern int dtor_idx_6161; // weak
// extern _UNKNOWN _gmon_start__; weak

//-------------------------------------------------------------------------
// Function declarations

void (*__cdecl init_proc())(void);
char *gets(char *s);
int puts(const char *s);
int __gmon_start__(void); // weak
void exit(int status);
void __cdecl _do_global_dtors_aux();
int __cdecl frame_dummy();
void __cdecl CanNeverExecute();
int __cdecl GetInput();
int __cdecl main();
int *__cdecl _libc_csu_init();
void __cdecl _i686_get_pc_thunk_bx();
void (*__cdecl _do_global_ctors_aux())(void);
void __cdecl term_proc();


//----- (080482F0) --------------------------------------------------------
void (*__cdecl init_proc())(void)
{
  if ( &_gmon_start__ )
    __gmon_start__();
  frame_dummy();
  return _do_global_ctors_aux();
}
// 8048350: using guessed type int __gmon_start__(void);

//----- (08048380) --------------------------------------------------------
#error "8048383: positive sp value has been found (funcsize=2)"

//----- (080483B0) --------------------------------------------------------
void __cdecl _do_global_dtors_aux()
{
  int v0; // eax@2
  int i; // ebx@2

  if ( !completed_6159 )
  {
    v0 = dtor_idx_6161;
    for ( i = ((signed int)(&_DTOR_END__ - (_UNKNOWN *)_DTOR_LIST__) >> 2) - 1;
          dtor_idx_6161 < (unsigned int)i;
          v0 = dtor_idx_6161 )
    {
      dtor_idx_6161 = v0 + 1;
      ((void (*)(void))_DTOR_LIST__[dtor_idx_6161])();
    }
    completed_6159 = 1;
  }
}
// 8049F1C: using guessed type int _DTOR_LIST__[];
// 804A01C: using guessed type char completed_6159;
// 804A020: using guessed type int dtor_idx_6161;

//----- (08048410) --------------------------------------------------------
int __cdecl frame_dummy()
{
  int result; // eax@1

  result = _JCR_LIST__;
  if ( _JCR_LIST__ )
    result = 0;
  return result;
}
// 8049F24: using guessed type int _JCR_LIST__;

//----- (08048434) --------------------------------------------------------
void __cdecl CanNeverExecute()
{
  puts("I can never execute");
  exit(0);
}

//----- (08048452) --------------------------------------------------------
int __cdecl GetInput()
{
  char s; // [sp+18h] [bp-10h]@1

  gets(&s);
  return puts(&s);
}

//----- (08048470) --------------------------------------------------------
int __cdecl main()
{
  GetInput();
  return 0;
}

//----- (08048490) --------------------------------------------------------
int *__cdecl _libc_csu_init()
{
  init_proc();
  return &_CTOR_LIST__;
}
// 8049F14: using guessed type int _CTOR_LIST__;

//----- (08048502) --------------------------------------------------------
void __cdecl _i686_get_pc_thunk_bx()
{
  ;
}

//----- (08048510) --------------------------------------------------------
void (*__cdecl _do_global_ctors_aux())(void)
{
  void (*result)(void); // eax@1
  int *v1; // ebx@2

  result = (void (*)(void))_CTOR_LIST__;
  if ( _CTOR_LIST__ != -1 )
  {
    v1 = &_CTOR_LIST__;
    do
    {
      --v1;
      result();
      result = (void (*)(void))*v1;
    }
    while ( *v1 != -1 );
  }
  return result;
}
// 8049F14: using guessed type int _CTOR_LIST__;

//----- (0804853C) --------------------------------------------------------
void __cdecl term_proc()
{
  _do_global_dtors_aux();
}

#error "There were 1 decompilation failure(s) on 11 function(s)"
